export const filterOptions = [
  { display: "Breakfast", key: "hasBreakfast" },
  { display: "Dinner", key: "isDinner" },
  { display: "Fast Food", key: "isFastFood" },
  { display: "Restaurant", key: "isRestaurant" },
  { display: "Fancy", key: "isFancy" },
  { display: "Pizza", key: "hasPizza" },
  { display: "Subs", key: "hasSubs" },
  { display: "Wings", key: "hasWings" },
  { display: "Steakhouse", key: "isSteakhouse" }
];

export const restaurants = [
  {
    name: "Taco Bell",
    hasBreakfast: true,
    isDinner: true,
    isFastFood: true,
    isRestaurant: false,
    isFancy: false,
    hasPizza: false,
    hasSubs: false,
    hasWings: false,
    isSteakhouse: false
  },
  {
    name: "KFC",
    hasBreakfast: false,
    isDinner: true,
    isFastFood: true,
    isRestaurant: false,
    isFancy: false,
    hasPizza: false,
    hasSubs: false,
    hasWings: false,
    isSteakhouse: false
  },
  {
    name: "Chick-Fil-A",
    hasBreakfast: true,
    isDinner: true,
    isFastFood: true,
    isRestaurant: false,
    isFancy: false,
    hasPizza: false,
    hasSubs: false,
    hasWings: false,
    isSteakhouse: false
  },
  {
    name: "Applebees",
    hasBreakfast: false,
    isDinner: true,
    isFastFood: true,
    isRestaurant: true,
    isFancy: false,
    hasPizza: false,
    hasSubs: false,
    hasWings: false,
    isSteakhouse: true
  },
  {
    name: "Logan",
    hasBreakfast: false,
    isDinner: true,
    isFastFood: false,
    isRestaurant: true,
    isFancy: true,
    hasPizza: false,
    hasSubs: false,
    hasWings: false,
    isSteakhouse: true
  },
  {
    name: "Texas Roadhouse",
    hasBreakfast: false,
    isDinner: true,
    isFastFood: false,
    isRestaurant: true,
    isFancy: true,
    hasPizza: false,
    hasSubs: false,
    hasWings: false,
    isSteakhouse: true
  },
  {
    name: "Bobs",
    hasBreakfast: true,
    isDinner: true,
    isFastFood: false,
    isRestaurant: true,
    isFancy: false,
    hasPizza: false,
    hasSubs: false,
    hasWings: false,
    isSteakhouse: false
  },
  {
    name: "McDonalds",
    hasBreakfast: true,
    isDinner: true,
    isFastFood: true,
    isRestaurant: false,
    isFancy: false,
    hasPizza: false,
    hasSubs: false,
    hasWings: false,
    isSteakhouse: false
  },
  {
    name: "Wendy's",
    hasBreakfast: true,
    isDinner: true,
    isFastFood: true,
    isRestaurant: false,
    isFancy: false,
    hasPizza: false,
    hasSubs: false,
    hasWings: false,
    isSteakhouse: false
  },
  {
    name: "Burger King",
    hasBreakfast: true,
    isDinner: true,
    isFastFood: true,
    isRestaurant: false,
    isFancy: false,
    hasPizza: false,
    hasSubs: false,
    hasWings: false,
    isSteakhouse: false
  },
  {
    name: "Rubi's",
    hasBreakfast: false,
    isDinner: true,
    isFastFood: true,
    isRestaurant: false,
    isFancy: false,
    hasPizza: true,
    hasSubs: false,
    hasWings: true,
    isSteakhouse: false
  },
  {
    name: "Pizza Place",
    hasBreakfast: false,
    isDinner: true,
    isFastFood: true,
    isRestaurant: false,
    isFancy: false,
    hasPizza: true,
    hasSubs: true,
    hasWings: true,
    isSteakhouse: false
  },
  {
    name: "Los Agaves",
    hasBreakfast: false,
    isDinner: true,
    isFastFood: false,
    isRestaurant: true,
    isFancy: false,
    hasPizza: false,
    hasSubs: false,
    hasWings: false,
    isSteakhouse: false
  },
  {
    name: "Popeyes",
    hasBreakfast: false,
    isDinner: true,
    isFastFood: true,
    isRestaurant: false,
    isFancy: false,
    hasPizza: false,
    hasSubs: false,
    hasWings: false,
    isSteakhouse: false
  },
  {
    name: "Cook sumn",
    hasBreakfast: true,
    isDinner: true,
    isFastFood: false,
    isRestaurant: false,
    isFancy: false,
    hasPizza: false,
    hasSubs: false,
    hasWings: false,
    isSteakhouse: false
  },
  {
    name: "Chinese",
    hasBreakfast: false,
    isDinner: true,
    isFastFood: true,
    isRestaurant: true,
    isFancy: false,
    hasPizza: false,
    hasSubs: false,
    hasWings: false,
    isSteakhouse: false
  },
  {
    name: "Bourbon Chicken",
    hasBreakfast: false,
    isDinner: true,
    isFastFood: true,
    isRestaurant: false,
    isFancy: false,
    hasPizza: false,
    hasSubs: false,
    hasWings: false,
    isSteakhouse: false
  },
  {
    name: "Penn Station",
    hasBreakfast: false,
    isDinner: true,
    isFastFood: true,
    isRestaurant: false,
    isFancy: false,
    hasPizza: false,
    hasSubs: true,
    hasWings: false,
    isSteakhouse: false
  },
  {
    name: "Smitty's",
    hasBreakfast: false,
    isDinner: true,
    isFastFood: true,
    isRestaurant: false,
    isFancy: false,
    hasPizza: true,
    hasSubs: false,
    hasWings: true,
    isSteakhouse: false
  },
  {
    name: "Domino's",
    hasBreakfast: false,
    isDinner: true,
    isFastFood: true,
    isRestaurant: false,
    isFancy: false,
    hasPizza: true,
    hasSubs: true,
    hasWings: true,
    isSteakhouse: false
  },
  {
    name: "Papa John's",
    hasBreakfast: false,
    isDinner: true,
    isFastFood: true,
    isRestaurant: false,
    isFancy: false,
    hasPizza: true,
    hasSubs: false,
    hasWings: true,
    isSteakhouse: false
  },
  {
    name: "Arby's",
    hasBreakfast: false,
    isDinner: true,
    isFastFood: true,
    isRestaurant: false,
    isFancy: false,
    hasPizza: false,
    hasSubs: false,
    hasWings: false,
    isSteakhouse: false
  },
  {
    name: "B-Dubs",
    hasBreakfast: true,
    isDinner: true,
    isFastFood: false,
    isRestaurant: true,
    isFancy: true,
    hasPizza: false,
    hasSubs: false,
    hasWings: true,
    isSteakhouse: false
  },
  {
    name: "Wings Etc",
    hasBreakfast: false,
    isDinner: true,
    isFastFood: false,
    isRestaurant: true,
    isFancy: true,
    hasPizza: false,
    hasSubs: false,
    hasWings: true,
    isSteakhouse: false
  },
  {
    name: "Smoke Sumn",
    hasBreakfast: false,
    isDinner: true,
    isFastFood: false,
    isRestaurant: false,
    isFancy: false,
    hasPizza: false,
    hasSubs: false,
    hasWings: false,
    isSteakhouse: false
  },
  {
    name: "IHOP",
    hasBreakfast: true,
    isDinner: true,
    isFastFood: false,
    isRestaurant: true,
    isFancy: true,
    hasPizza: false,
    hasSubs: false,
    hasWings: false,
    isSteakhouse: false
  },
  {
    name: "Longhorn",
    hasBreakfast: false,
    isDinner: true,
    isFastFood: false,
    isRestaurant: true,
    isFancy: true,
    hasPizza: false,
    hasSubs: false,
    hasWings: false,
    isSteakhouse: true
  },
  {
    name: "Rivertown Grill",
    hasBreakfast: false,
    isDinner: true,
    isFastFood: false,
    isRestaurant: true,
    isFancy: true,
    hasPizza: false,
    hasSubs: false,
    hasWings: false,
    isSteakhouse: false
  },
  {
    name: "Outback",
    hasBreakfast: false,
    isDinner: true,
    isFastFood: false,
    isRestaurant: true,
    isFancy: true,
    hasPizza: false,
    hasSubs: false,
    hasWings: false,
    isSteakhouse: true
  }
];
